services:
  nginx:
    image: nginx:latest
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.http.routers.nginx.rule=Host(`nginx.gabrielmelo.shop`)"
        - "traefik.http.routers.nginx.entrypoints=websecure"
        - "traefik.http.routers.nginx.tls.certresolver=leresolver"
        - "traefik.http.routers.nginx.service=nginx"
networks:
  public:
    external: true
    attachable: true