services:
  nginx:
    image: nginx:latest
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      labels:
        - traefik.enable=true
        - traefik.http.routers.nginx-http.rule=Host(`nginx.gabrielmelo.shop`)
        - traefik.http.routers.nginx-http.entrypoints=web
        - traefik.http.routers.nginx-https.tls=true
        - traefik.http.routers.nginx-https.tls.certresolver=leresolver
        - traefik.http.routers.nginx-https.entrypoints=websecure
        - traefik.http.routers.nginx-https.rule=Host(`nginx.gabrielmelo.shop`)
networks:
  public:
    external: true