global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: ERROR
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: public

certificatesResolvers:
  leresolver:
    acme:
      email: dev.gabrielmelo@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web