global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: ERROR
api:
  dashboard: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: public

certificatesResolvers:
  leresolver:
    acme:
      email: dev.gabrielmelo@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    dashboard:
      rule: Host(`traefik.gabrielmelo.shop`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$2y$05$R/fJVZL1wjSFnqWLstMnr.AdRmuMxcLrNkdDgPFe4H2RqFK97LjDq"